name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  flutter_riverpod: ^1.0.3
  retrofit: ^3.0.1
  shared_preferences: ^2.0.11
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  jwt_decoder: ^2.0.1
  infinite_scroll_pagination: ^3.1.0
  auto_route: ^3.2.1
  url_strategy: ^0.2.0
  json_annotation: ^4.4.0
  responsive_framework: ^0.1.5
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: null
  flutter_gen_runner: null
  freezed: 1.0.2
  auto_route_generator: ^3.2.1
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/env/
flutter_intl:
  enabled: true
